insert into ejercicios (nombre, descripcion, creado_por) values
('Press de banca', 'Ejercicio compuesto para trabajar el pecho con barra en banco plano.', null),
('Press inclinado con barra', 'Trabaja la parte superior del pecho en banco inclinado con barra.', null),
('Press declinado con barra', 'Enfocado en la parte inferior del pecho usando banco declinado.', null),
('Press de banca con mancuernas', 'Pecho con mancuernas en banco plano, mayor rango de movimiento.', null),
('Press inclinado con mancuernas', 'Pecho superior con mancuernas en banco inclinado.', null),
('Press declinado con mancuernas', 'Pecho inferior con mancuernas en banco declinado.', null),
('Aperturas con mancuernas', 'Aísla el pecho abriendo los brazos en banco plano.', null),
('Aperturas inclinadas con mancuernas', 'Aperturas para pecho superior en banco inclinado.', null),
('Aperturas en máquina', 'Aísla el pecho usando máquina de aperturas.', null),
('Fondos en paralelas', 'Ejercicio compuesto para pecho y tríceps en barras paralelas.', null),
('Press en máquina', 'Press de pecho guiado en máquina para mayor control.', null),
('Crossover en polea alta', 'Aperturas de pecho cruzando brazos con poleas altas.', null),
('Crossover en polea baja', 'Aperturas de pecho desde poleas bajas hacia arriba.', null),
('Pull over con mancuerna', 'Ejercicio para pecho y dorsal con mancuerna sobre banco.', null),
('Press militar con barra', 'Hombros, principalmente deltoides, de pie o sentado con barra.', null),
('Press militar con mancuernas', 'Hombros con mancuernas, sentado o de pie.', null),
('Press Arnold', 'Press de hombros con giro de mancuernas.', null),
('Elevaciones laterales con mancuernas', 'Aísla el deltoides lateral levantando mancuernas a los costados.', null),
('Elevaciones frontales con mancuernas', 'Trabaja el deltoides anterior levantando mancuernas al frente.', null),
('Elevaciones posteriores con mancuernas', 'Aísla el deltoides posterior inclinado hacia adelante.', null),
('Pájaros en peck deck', 'Deltoides posterior en máquina peck deck.', null),
('Remo al mentón con barra', 'Hombros y trapecio, barra desde muslos hasta el mentón.', null),
('Encogimientos de hombros con mancuernas', 'Trapecio elevando los hombros con mancuernas.', null),
('Encogimientos de hombros con barra', 'Trapecio elevando los hombros con barra.', null),
('Press de hombros en máquina', 'Press guiado para hombros en máquina.', null),
('Remo con barra', 'Espalda, barra desde el suelo hasta el abdomen inclinado.', null),
('Remo con mancuernas a una mano', 'Espalda, mancuernas apoyando rodilla y mano en banco.', null),
('Remo en máquina', 'Espalda, movimiento guiado en máquina de remo.', null),
('Remo en polea baja', 'Espalda, jalón horizontal con polea baja.', null),
('Jalón al pecho en polea alta', 'Espalda, barra desde polea alta al pecho.', null),
('Jalón tras nuca en polea alta', 'Espalda, barra desde polea alta detrás de la cabeza.', null),
('Dominadas pronas', 'Espalda, tracción en barra fija con agarre prono.', null),
('Dominadas supinas', 'Espalda, tracción en barra fija con agarre supino.', null),
('Peso muerto convencional', 'Espalda baja y piernas, barra desde el suelo hasta la cadera.', null),
('Peso muerto sumo', 'Variante de peso muerto con piernas abiertas.', null),
('Peso muerto rumano', 'Enfocado en isquiotibiales y glúteos, barra bajando con piernas semi extendidas.', null),
('Buenos días con barra', 'Espalda baja e isquiotibiales, inclinando el torso con barra en la espalda.', null),
('Hiperextensiones lumbares', 'Espalda baja, extensión de tronco en banco romano.', null),
('Jalón con agarre estrecho', 'Espalda, polea alta con agarre cerrado.', null),
('Remo invertido', 'Espalda, tracción del cuerpo bajo barra fija.', null),
('Sentadilla trasera', 'Piernas, barra sobre la espalda bajando en cuclillas.', null),
('Sentadilla frontal', 'Piernas, barra sobre los hombros al frente.', null),
('Sentadilla búlgara', 'Pierna trasera apoyada en banco, bajando en sentadilla.', null),
('Prensa de piernas', 'Piernas, empuje de plataforma en máquina.', null),
('Extensión de piernas en máquina', 'Cuádriceps, extensión de rodilla en máquina.', null),
('Curl femoral en máquina', 'Isquiotibiales, flexión de rodilla en máquina.', null),
('Zancadas con mancuernas', 'Piernas, paso largo hacia adelante con mancuernas.', null),
('Zancadas con barra', 'Piernas, paso largo hacia adelante con barra.', null),
('Desplantes caminando', 'Piernas, zancadas alternadas avanzando.', null),
('Elevación de talones de pie', 'Gemelos, elevando talones de pie.', null),
('Elevación de talones sentado', 'Gemelos, elevando talones sentado en máquina.', null),
('Abducción de cadera en máquina', 'Glúteos y abductores, separando piernas en máquina.', null),
('Aducción de cadera en máquina', 'Aductores, juntando piernas en máquina.', null),
('Hip thrust con barra', 'Glúteos, elevación de cadera con barra apoyada.', null),
('Puente de glúteos', 'Glúteos, elevación de cadera sin peso.', null),
('Curl de bíceps con barra', 'Bíceps, flexión de codo con barra de pie.', null),
('Curl de bíceps con mancuernas', 'Bíceps, flexión de codo con mancuernas alternadas.', null),
('Curl martillo con mancuernas', 'Bíceps y braquial, mancuernas con agarre neutro.', null),
('Curl concentrado', 'Bíceps, sentado apoyando el brazo en la pierna.', null),
('Curl en banco Scott', 'Bíceps, flexión de codo en banco predicador.', null),
('Curl de bíceps en polea baja', 'Bíceps, flexión de codo con polea baja.', null),
('Curl de bíceps en máquina', 'Bíceps, flexión de codo en máquina guiada.', null),
('Extensión de tríceps en polea alta', 'Tríceps, extensión de codo con cuerda o barra en polea alta.', null),
('Fondos de tríceps en paralelas', 'Tríceps, bajando el cuerpo entre barras paralelas.', null),
('Press francés con barra', 'Tríceps, extensión de codo acostado con barra.', null),
('Press cerrado con barra', 'Tríceps y pecho, press de banca con agarre cerrado.', null),
('Extensión de tríceps con mancuerna', 'Tríceps, extensión de codo con mancuerna sobre la cabeza.', null),
('Patada de tríceps con mancuerna', 'Tríceps, extensión de codo inclinado hacia atrás.', null),
('Extensión de tríceps en máquina', 'Tríceps, extensión de codo en máquina guiada.', null),
('Plancha abdominal', 'Core, mantener el cuerpo alineado apoyado en antebrazos.', null),
('Crunch abdominal', 'Core, flexión de tronco en el suelo.', null),
('Crunch en máquina', 'Core, flexión de tronco en máquina guiada.', null),
('Elevación de piernas colgado', 'Core, elevar piernas colgado de barra.', null),
('Elevación de piernas en banco', 'Core, elevar piernas acostado en banco.', null),
('Twist ruso', 'Core, rotación de tronco sentado con o sin peso.', null),
('Encogimientos laterales con mancuerna', 'Oblicuos, inclinación lateral con mancuerna.', null),
('Rueda abdominal', 'Core, extensión y flexión con rueda abdominal.', null),
('Mountain climbers', 'Core y cardio, llevar rodillas al pecho en posición de plancha.', null),
('Burpees', 'Full body, salto y flexión en el suelo.', null),
('Jumping jacks', 'Full body, saltos abriendo piernas y brazos.', null),
('Sentadilla con salto', 'Piernas y cardio, sentadilla seguida de salto.', null),
('Clean and press', 'Full body, levantamiento de barra desde el suelo y press por encima de la cabeza.', null),
('Thruster con barra', 'Sentadilla frontal seguida de press de hombros.', null),
('Swing con kettlebell', 'Full body, balanceo de pesa rusa entre piernas y por encima de la cabeza.', null),
('Farmer''s walk', 'Full body, caminar cargando peso en ambas manos.', null),
('Step up en banco', 'Piernas y glúteos, subir y bajar de un banco con peso.', null),
('Remo renegado', 'Espalda y core, remo con mancuernas en posición de plancha.', null),
('Box jump', 'Piernas y potencia, salto sobre caja o plataforma.', null),
('Battle ropes', 'Full body, mover cuerdas pesadas de forma explosiva.', null),
('Sprints en cinta', 'Cardio y piernas, carreras rápidas en cinta.', null),
('Remo energético en máquina', 'Full body, remo intenso en máquina de remo.', null),
('Escalador en máquina', 'Cardio y piernas, subir escalones en máquina.', null),
('Caminata en cinta inclinada', 'Cardio y piernas, caminar en cinta con inclinación.', null),
('Bicicleta fija', 'Cardio y piernas, pedaleo en bicicleta estática.', null),
('Elíptico', 'Cardio y full body, movimiento elíptico en máquina.', null),
('Remo con banda elástica', 'Espalda, tracción con banda elástica.', null),
('Press de pecho con banda elástica', 'Pecho, empuje con banda elástica.', null),
('Sentadilla con banda elástica', 'Piernas, sentadilla usando banda elástica.', null),
('Face pull en polea', 'Espalda y hombros, tracción de cuerda hacia la cara.', null),
('Press pallof en polea', 'Core, empuje anti-rotacional con polea.', null),
('Plancha lateral', 'Core y oblicuos, mantener el cuerpo alineado de lado.', null),
('Ab wheel rollout', 'Core, extensión y flexión con rueda abdominal.', null),
('Skipping', 'Cardio, saltar la soga a ritmo.', null),
('Escalera de agilidad', 'Cardio y coordinación, ejercicios rápidos en escalera de piso.', null),
('Wall ball', 'Full body, lanzar balón medicinal contra la pared.', null),
('Lanzamiento de balón medicinal', 'Full body, lanzar balón medicinal al suelo o al frente.', null),
('Peso muerto a una pierna', 'Isquiotibiales y glúteos, peso muerto con una pierna.', null),
('Step down', 'Piernas, bajar de un banco controlando el movimiento.', null),
('Plancha con toque de hombro', 'Core y hombros, tocar hombros alternando en posición de plancha.', null),
('Plancha con elevación de pierna', 'Core y glúteos, plancha elevando una pierna.', null),
('Plancha con rotación', 'Core y oblicuos, plancha girando el tronco.', null);
